gb_creation_home_homepage:
    pattern:  /
    defaults: { _controller: GbCreationHomeBundle:Home:index }
    requirements:
        _method:  GET

gb_creation_home_feed_rss:
    pattern:  /
    defaults: { _controller: GbCreationHomeBundle:Home:feedRss }
    requirements:
        _method:  POST

gb_creation_contact:
    pattern:  /contact
    defaults: { _controller: GbCreationHomeBundle:Contact:contact }
    requirements:
        _method:  GET|POST
